### ISSUE TITLE
왜 그래픽스는 배우기 어려운 걸까? [스터디 목표]

### ISSUE THREAD

**Issue by Wongyu-Shin** [Graphics101/Graphics101#1]
2024 현 시점, 그래픽스에 대한 다양한 도서와 웹 문서등 학습 자료는 수없이 많이 찾아 볼 수 있다.
하지만, 왜 아직도 우리는 그래픽스를 학습하기를 어려워하고 시작을 두려워하는걸까?

잠깐의 조사에도 OpenGL, 혹은 WebGL 의 학습을 도와주는 웹 사이트를 3군데 정도 찾을 수 있었다.

1. LearnOpenGL
https://learnopengl.com/Introduction
OpenGL의 시작부터, PBR(물리 기반 렌더링) 까지 넓은 영역에 대한 다양한 자료를 찾을 수 있는 페이지.
장점: 많은 양의 자료들
단점: 많은 양의 자료들(너무 많은 자료들 앞에서 압도되거나, 어디서부터 시작해야할지 알기 어려운 느낌.) 영어 자료인것도 장벽중 하나.

2. BookOfShader
https://thebookofshaders.com/?lan=kr
LearnOpenGL이 'OpenGL' 그래픽 라이브러리 전반을 설명하는데 집중한다면, BookOfShader 는 그래픽 라이브러리의 일부분인 쉐이더 코드,
그 중 어떤 색상을 화면에 표시해야하는지를 다루는 'Fragment Shader' 의 학습에 대해 다루고 있다.
장점: 한국어 지원, 친절한 백그라운드에 대한 설명들.
단점: 좁은 영역에 대해서만 다루고 있다.
이걸 다 읽는다 해도 그래픽스 전반을 알수는 없을것 같다.

3. ShaderToy
https://www.shadertoy.com/
실제로 동작하는 멋진 예제와 코드를 공유하는 사이트.
장점: 동작하는 코드와 예제들.
단점: 충분한 지식이 없다면, 이 코드의 의미를 하나도 알 수 없다.

이러한 3개의 사이트를 보고 느낀점은,
양질의 자료는 이미 많이 존재한다. 근대 왜 우리는 그래픽스 공부가 어렵다고 생각할까?

이유는 이러한 자료를 찾기 어려운것이 아니라, 찾아도 이해할 수 있는 백그라운드 지식이 부족하기 때문이다. 

조금 더 자세히 설명하면, 운동을 시작할 때 기초 체력을 먼저 기르는것 처럼 컴퓨터 그래픽스에 대한 정말 기본적인 기반지식 학습을 
Cpp, ShaderCode, Graphics Library  에 대한 기반지식이 적거나 아예 없는 사람을 대상으로

충분한 기반지식을 갖추어 스스로 야생학습을 진행 할 수 있을정도의 기초 체력을 만들어주면 
이후에는 이제 스스로 원하는 관심사에 대해 학습해 나갈 수 있을것이다 라는 가설을 세울 수 있다.

**Comment by Wongyu-Shin** [comment]
가설을 검증하기 위해, 진행하는 스터디는 OpenGL ES 3.0 혹은 WebGL 2 를 기반으로, 그래픽스 전반의 배경지식을 학습하는것을 목표로
하는게 어떨까요? @mkitwave 
 
이를 진행하는데 참고할만한 자료가 있는지 조금 더 알아보겠습니다.

이전에 다른 팀에서의 추천은 영어 자료를 기반으로 학습하는것을 추천받았지만, 음.... 일단 자료가 읽혀야지 뭘 공부하던가 말던가 할 수 있다고 생각해요.

한국어 자료를 최우선으로 찾아보고, 오역이 너무 심할 경우나 자료의 질이 너무 떨어질 경우에만 2순위로 영어 자료를 선택하는것으로 진행해볼께요.

참고할만한 기반 자료를 찾고, 구체적인 방향을 결정하는 식으로 가는게 어떨까 싶습니다.

**Comment by Wongyu-Shin** [comment]
https://webgl2fundamentals.org/webgl/lessons/ko/webgl-fundamentals.html
이런 한국어 자료도 있군요!

https://pikuma.com/courses/learn-3d-computer-graphics-programming
영어이긴 하지만, GL과 같은 라이브러리를 아예 안 쓰고 밑바닥 부터 직접 구현하는 강의도 찾았습니다.

**Comment by Wongyu-Shin** [comment]
영어에다가 좀 (많이) 오래되었지만, 그래픽 렌더 파이프라인 전 과정을 설명하는 포스트 시리즈를 발견했습니다.
https://fgiesen.wordpress.com/2011/07/09/a-trip-through-the-graphics-pipeline-2011-index/ 

요건 그래픽스하고는 조금... 떨어저 있긴 하지만 간단한 천 물리 시뮬레이션을 구현하는 포스트네요
https://pikuma.com/blog/verlet-integration-2d-cloth-physics-simulation

**Comment by Wongyu-Shin** [comment]
주말동안 스터디를 진행하며 얻을 수 있는 두개의 가치를 어떻게 하면 적절한 벨런스를 가질 수 있는지에 대해 고민해보았습니다.
제가 생각하는 스터디에서 구성원에게 주어야하는 가장 큰 두 가치는 바로 아래와 같은데요,
'성취감으로 인한 리탠션 유지' && '그래픽스 개발 역량 상승' 

개발 역량 상승을 위해 너무 과도한 과제를 부여하면, 난도에 압도되어 더 이상 스터디를 진행하고자 하는 리텐션 유지가 어렵고,
그렇다고 너무 쉬운 과제만 진행한다면, 결국 스터디 참여의 가장 큰 동기인 그래픽스 개발 역량 상승을 달성하기 힘들다 생각되어 리탠션이 떨어 질 수 있다 생각했습니다.

이 두개를 적절히 가져갈 수 있는 아이디어가 하나 생각났는데요,
스터디를 진행하며 학습한 내용을 문서화 하고, 문서화 도구는 Obsidian 을 사용합니다.
그 뒤, Obsidian 을 publish 해서 이를 개발 커뮤니티에 공유해보는건 어떨까? 생각해보았어요.
 
 Obsidian 의 publish 는 유료 기능이지만, 커뮤니티에서 무료 퍼블리싱 플러그인들을 제공하는걸 찾았습니다.
 https://anpigon.tistory.com/203
 
 2주를 한 스프린트로 잡고, 1주차는 새로운 지식을 학습 -> 2주차는 학습한 내용을 문서화 해 배포.
 이러한 사이클로 가면 어떨까? 생각이 드는데요, 아직 확정은 아니고 아이디어 이기 때문에 다른 의견이 있다면 자유롭게 제시해주셔도 됩니다.
 @mkitwave

**Comment by mkitwave** [comment]
작성해주신 스터디 가치는 매우 공감합니다 : )
다만 문서화를 진행하는 툴은 Gitbook이 더 나을 수도 있겠다는 생각이 들었어요.
이유는 다음과 같습니다.

- 기본으로 publish 기능 지원
- draft, github PR, review 등의 기능을 GUI로 지원 ([참고](https://gitbook.solbox.com/overview/co-working))
- Obsidian의 경우 문서가 알파벳 순으로 정렬되는 것으로 알고 있음 -> Gitbook은 커스터마이즈 가능

Obsidian과 Gitbook을 둘 다 위키 목적으로 사용해봤었는데요, Obsidian의 불편함에 Gitbook으로 갈아탔었어요. 
각자 장단점이 있겠지만 개인적 경험으로 Gitbook을 추천합니다 : )

**Comment by Wongyu-Shin** [comment]
오 좋습니다! 
퍼블리싱의 불편함이 해결된다면 더할 나위 없죠!
약간 걱정됬던게 iframe 의 형식으로 webGL 예제를 첨부 할 수 있을까?  && 백링크 지원이 가능할까? 였는데,
https://docs.gitbook.com/content-editor/blocks/embed-a-url
예제 첨부는 일단 가능한것 같습니다.

draft, github PR, review 등의 기능을 GUI로 지원 요 기능은 아주 마음에 드네요!
아예 마지막 기여자 깃헙 프로필이 문서에 뜨도록 설정할 수 잇었으면 좋겠네요 동기부여의 측면으로 사용하게요 ㅋㅋㅋ

**Comment by Wongyu-Shin** [comment]
@mkitwave 
여기서 나눴던 이야기를 정리해 간단하게 리드미를 작성 해보았습니다!
시간 나실때 한번 확인부탁드려요~~!

PRlink: https://github.com/Graphics101/Graphics101/pull/2
